#pragma once

#include "Features/DB2/DB2File.hpp"
#include "Features/DB2/DB2Mgr.hpp"

// ModelFilePath.db2 (generated by Db2Gen from the listfile): FileDataID -> model-asset path.
// Covers .m2/.wmo/.skin/.anim/.phys/.bone. WDC1, inline id, one string field.
namespace wraith::features::db2::defs
{
    struct ModelFilePathRow
    {
        uint32_t id;     // FileDataID
        int32_t  path;   // string offset
    };

    class ModelFilePath : public DB2Table<ModelFilePathRow>
    {
    public:
        static ModelFilePath& Get()
        {
            static ModelFilePath instance;
            if (!instance.IsLoaded())
            {
                instance.Load("ModelFilePath.db2");
                Track(&instance, "ModelFilePath.db2");
            }
            return instance;
        }

        // Resolve a FileDataID to its path, or nullptr if absent.
        const char* Path(uint32_t fileDataId)
        {
            const auto* r = Find(static_cast<int32_t>(fileDataId));
            return r ? Str(static_cast<uint32_t>(r->path)) : nullptr;
        }
    };
}
