#pragma once

#include "Features/DB2/DB2File.hpp"
#include "Features/DB2/DB2Mgr.hpp"

// TextureFilePath.db2 (generated by Db2Gen from the listfile): FileDataID -> texture path.
// WDC1, inline id, one string field. Resolves a .blp FileDataID to its path string.
namespace wraith::features::db2::defs
{
    struct TextureFilePathRow
    {
        uint32_t id;     // FileDataID
        int32_t  path;   // string offset
    };

    class TextureFilePath : public DB2Table<TextureFilePathRow>
    {
    public:
        static TextureFilePath& Get()
        {
            static TextureFilePath instance;
            if (!instance.IsLoaded())
            {
                instance.Load("TextureFilePath.db2");
                Track(&instance, "TextureFilePath.db2");
            }
            return instance;
        }

        // Resolve a FileDataID to its path, or nullptr if absent.
        const char* Path(uint32_t fileDataId)
        {
            const auto* r = Find(static_cast<int32_t>(fileDataId));
            return r ? Str(static_cast<uint32_t>(r->path)) : nullptr;
        }
    };
}
